### ISSUE TITLE
Unintuitive installation procedure for Sylvan

### ISSUE THREAD

**Issue by SSoelvsten** [trolando/sylvan#10]
I'm working on creating a repository that contains benchmarks implemented with different OBDD packages. Before I try to write my own code using Sylvan, I would like to be sure I can build and run the current N-Queens example.

## Expected way to include Sylvan within CMake:

The project structure is as follows
```
|- CMakeLists.txt
|- external/
|  |- sylvan/
|- src/
|  |- CMakeLists.txt
|  |- sylvan_queens.cpp
```
Where based on my understanding of how to use CMake I would expect `./CMakeLists.txt` should be as follows
```
add_subdirectory (external/sylvan sylvan)
add_subdirectory (src)
```
and `./src/CMakeLists.txt` as follows
```
add_executable(sylvan_queens sylvan_queens.cpp)
target_link_libraries(sylvan_queens sylvan)
```

At this point I would expect to have linked everything to be able to build the Sylvan queens example as follows
```
mkdir -p build/ && cd build/
cmake ..
make sylvan_queens
```

## Actual result:

With only the above, then during compilation, the linker is not capable of finding the _Sylvan_ files as shown below
```
/obdd-benchmark/src/sylvan/queens.cpp:14:10: fatal error: sylvan.h: No such file or directory
 #include <sylvan.h>
          ^~~~~~~~~~
```

Instead one has to install Sylvan separately as described in the documentation, which at the time of writing this issue is as follows
```
mkdir external/sylvan/build && cd external/sylvan/build
cmake ..
sudo make
sudo make install
```

## Final comments:

From experience with other libraries, such as [TPIE](https://github.com/thomasmoelhave/tpie) it is possible to do merely as shown above. I suspect one would have to compare the following two files to find out how to do so

- **TPIE**: [`tpie/CMakeLists.txt`](https://github.com/thomasmoelhave/tpie/blob/master/tpie/CMakeLists.txt)

- **Sylvan**: [`src/CMakeLists.txt`](https://github.com/trolando/sylvan/blob/master/src/CMakeLists.txt)

I definitely notice, that the header files for Sylvan are not included as part of the `add_library`, but they are instead only placed in the installation directory. That seems to be in line with the observed behaviour.

**Comment by trolando** [comment]
Hej @SSoelvsten ,

What would be the ideal remedy? I have not really looked closely at how other people use the library in practice, as the number of users has either remained relatively low, or no one bothered to give this feedback. When back home, I could take a look at how TPIE does it? Is their solution the ideal way, or are there other libraries that serve as an example to how to do this?

**Comment by SSoelvsten** [comment]
I'm not at all an expert on CMake, so I cannot tell whether the usage in TPIE is as it is supposed to be. For that, you would have to double-check with the developers of said project. They for example do something a little weird to allow imports to be of the form `<tpie/file_name.h>` rather than having all files be named `<tpie_file_name.h>`. What I can say though is, that their setup works simply with the `add_subdirectory` which seems to be the intention with CMake.

I'm incapable of testing how a change in the CMakeLists.txt file would affect the build, since the prior installation of Sylvan by the documentation seems to make it globally available for CMake?

**Comment by SSoelvsten** [comment]
Now looking at recreating examples with _BuDDy_ they also have some weird setup, that essentially requires one to directly link to the source code folder:
```
add_executable(buddy_queens buddy_queens.cpp)
target_include_directories(buddy_queens PRIVATE ../external/BuDDy/src)
target_link_libraries(buddy_queens buddy)
```
Which also seems to me quite wrong?

Is it possible to run the install script if yet uninstalled automatically, when the folder is included as a subdirectory? That might be the smallest and easiest solution for you?

**Comment by SSoelvsten** [comment]
Now that I am setting this up to run on a shared supercomputer, where I have no _sudo_ access, then this turns out to be a much more pressing issue for me. The `make install` script requires root access to create folders and files in the `usr/local` directory.

Is there a simple work-around, that one can do?

**Comment by trolando** [comment]
Can't you just use `cmake --install /path/to/install` or `cmake -DCMAKE_INSTALL_PREFIX=/path/to/install` or `make DESTDIR=/path/to/install` ?

**Comment by SSoelvsten** [comment]
Thank you for that pointer. I did not know those variables existed; I did not think of trying to read the auto-generated files for such a variable. After about two or three hours of getting it to work, it runs.

You can see the CMake and Makefile changes needed to do so on the following commit

- https://github.com/SSoelvsten/bdd-benchmark/commit/22ff640e82f183b0681bb8ca4babdca9690be733

I do not know, whether you believe this is a 'hack' or as intended?

**Comment by trolando** [comment]
By the way whatever happens in my master branch right now is ugly force pushing (just the top) but since you're apparently way deeper into the whole doing-CMake-correctly thing, is whatever I'm doing making more sense?

In a more ideal world I would understand and apply whatever https://alexreinking.com/blog/building-a-dual-shared-and-static-library-with-cmake.html is trying to make me do, but I'm also running out of academic time ;-) so much to do...

**Comment by SSoelvsten** [comment]
I have neither figured out how not to do ugly force pushes to trigger and test continuous integration the very first time around it is added to the repo. On the bright side, after the first time you are happy with it, you can do all of your changes (Sylvan, CMake, or to the Actions themselves) on a separate branch to then pull request them into master. Then you can force push to your hearts content on that branch as much as you want without worrying too much about people pulling. Feature branches and so on may feel weird at first, but one quickly gets into the groove and work faster.

My CMake proficiency is neither the best. I usually also just google around for multiple things and cry until it works. ;-) I went over to my [BDD Benchmark](https://github.com/SSoelvsten/bdd-benchmark) repository and pulled the newest of `master`. I can say this:
- I removed the `set(SYLVAN_INCLUDE_DIR "...")` and all of the `target_include_directories(<benchmark-target> "${SYLVAN_INCLUDE_DIR}")` and locally I can still get the Sylvan versions of all benchmarks to run.
- I cannot remember whether my computer is "polluted" with some global settings of installing Sylvan, but when I stop using `target_link_libraries(<benchmark-target> sylvan)` where `sylvan` is merely obtained from `add_subdirectory (external/sylvan sylvan)` it does not work.

So, I think you resolved this issue too. ^_^

I read through 2d5d83d7cc2ae5d177c596efa5a5d855f26bb51c and in _examples/CMakeLists.txt_ you can define a macro to not have to copy paste all of the options on each target. TPIE [defines macros](https://github.com/SSoelvsten/tpie/blob/master/test/CMakeLists.txt#L15) to do just that for their unit tests. But, that really is _all_ I could find, that didn't seem to "make sense".

**Comment by trolando** [comment]
Yeah I think I should use a similar macro, good idea for later. I'll leave this issue open for that.

In theory, one should be able to use sylvan simply by adding subdirectory and linking with `sylvan::sylvan` or `sylvan`, or if installed, with `find_package`.

I'd use feature branches more if I were a bit more disciplined on this. On the other side, the number of active users that I have that are eagerly pulling the master branch and developing against the cutting edge is very low, so that's fine :-)

**Comment by trolando** [comment]
In fact, I have a couple such branches, such as the `zdd` stuff. And the `tbdd` branch. I may get to merging that relatively soon.

**Comment by SSoelvsten** [comment]
I only have discipline, because I was forced to do so for a year in the "filthy" industry, and I have kept it since. :D With so few, you are right it does not hurt so much to do `git fetch && git reset --hard origin/master` a few times.

They seem like great ways to test whether the actions work as intended.

**Comment by trolando** [comment]
I think I've now resolved these issues in the master branch.
