### ISSUE TITLE
Build error due to deprecation on macOS

### ISSUE THREAD

**Issue by AlexBork** [trolando/sylvan#13]
While trying to build sylvan on macOS 11.3 using Apple Clang 12.0.5 and the latest version of the xcode command line tools I run into the following issue:
```console
/Users/bork/sylvan/src/lace.c:496:9: error: 'sem_init' is deprecated [-Werror,-Wdeprecated-declarations]
        sem_init(&et.sem, 0, 0);
        ^
/Users/bork/sylvan/src/lace.c:503:9: error: 'sem_destroy' is deprecated [-Werror,-Wdeprecated-declarations]
        sem_destroy(&et.sem);
        ^
/Users/bork/sylvan/src/lace.c:694:5: error: 'sem_init' is deprecated [-Werror,-Wdeprecated-declarations]
    sem_init(&suspend_semaphore, 0, 0);
    ^
/Users/bork/sylvan/src/lace.c:911:5: error: 'sem_destroy' is deprecated [-Werror,-Wdeprecated-declarations]
    sem_destroy(&suspend_semaphore);
    ^
```

**Comment by trolando** [comment]
Yes I am now aware of this issue, it's fairly annoying that MacOS does not implement semaphores. 

I guess I need some solution like
- https://izziswift.com/why-are-sem_init-sem_getvalue-sem_destroy-deprecated-on-mac-os-x-and-what-replaces-them/
- https://izziswift.com/posix-semaphores-on-mac-os-x-sem_timedwait-alternative/
something along those lines. I'll get back to this later.

**Comment by trolando** [comment]
This is now fixed in Lace (github.com/trolando/lace). I will patch Sylvan in the future.

**Comment by trolando** [comment]
This is now patched. However there are errors in Travis on MacOSX (https://travis-ci.com/github/trolando/sylvan) that I cannot resolve, since I do not currently have a Mac. There are somehow segmentation faults on the OSX builds in the test programs, and despite installing argp-standalone in homebrew, the compiler cannot find argp.h. If you can assist with that, I would be happy.

**Comment by trolando** [comment]
Also, I will need to migrate away from Travis. Just one evening of fixing builds and some small issues and now Travis wants me to pay? 👎 

Going to have a good look at https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by SSoelvsten** [comment]
If you need help migrating from Travis CI to (the free) GitHub Actions, you just ask me. :)

**Comment by trolando** [comment]
Yeah, that was useful. I've got Github Actions working mostly on Lace and Sylvan, now trying to synchronize things a bit.
