### ISSUE TITLE
About reference in sylvan_obj.cpp

### ISSUE THREAD

**Issue by zhangyedi** [trolando/sylvan#14]
I notice that there are no functions to update the reference in sylvan_obj.cpp, just like "example/simple.cpp" (which is a simple task written with sylvan_obj). So I wonder when do I need to update the reference manually, like using Sylvan.sylvan_ref().

**Comment by trolando** [comment]
The object oriented variant has a reference using the pointer. See lines 38-41 of sylvan_obj.hpp for example. When you create a new Bdd object, the Bdd is automatically referenced via pointer with the call to sylvan_protect, so not via the value. Any time you change the Bdd, this is fine you don't need to update. Then when the Bdd is deleted, the pointer is removed again (line 42 the ~Bdd method). This way you don't need to think too much about references when you use the C++ class.
