### ISSUE TITLE
Documentation has moved

### ISSUE THREAD

**Issue by michaelcadilhac** [trolando/sylvan#15]
Hi there,
GitHub pages have moved; the documentation is now at https://trolando.github.io/sylvan/.  This documentation seems to be dated, by the way.
Cheers,
M.

**Comment by trolando** [comment]
Yeah I might need to update it. Why did the documentation move? Did github.io change something in their setup?

**Comment by michaelcadilhac** [comment]
Sorry, my message was a bit terse.  The old url, as you have in your README,  ended in github.com; it now has to be github.io (since April 15 it seems).  Thanks!

**Comment by trolando** [comment]
Yeah I figured that out now. I'll have to give that an update. Keeping this open until I do that.
