### ISSUE TITLE
High CPU Usage even after calls to sylvan functions have returned

### ISSUE THREAD

**Issue by allrtaken** [trolando/sylvan#23]
Hello,

My program consists of 3 phases in which Sylvan is used in first two phases:
1) Construct MTBDDs using external API operations like sum/product/abstract etc
2) Traverse the constructed MTBDDs to create a custom copy of the mtbdd DAGs represented using my own sylvan-independent datastructure. I use mtbdd_gethigh/low,  as well as  sylvan internals like MTBDD_GETNODE and mtbdd_getvar.  I store mtbddnode_t values returned by MTBDD_GETNODE in an stl unordered_map to ensure I'm not re-processing already visited nodes
3) Perform operations on my datastructure created in phase 2, without using sylvan in anyway

My program is running without errors to completion in both cases when n_workers is set to 0 (auto detect) as well as 1 (single threaded). However, I noticed that when n_workers is set to 0 (running 8 threads since there are 8 cores on my pc), the CPU usage remains at close to 800% even in phase 3 (i.e. after all sylvan operations should have ceased). This is unexpected because I am not doing any multithreading in my program (or interacting with LACE) in phase 3. The running time of phase 3 is actually taking a hit as compared to running with n_workers set to 1. Ideally, I would like to use multiple threads only in phase 1, while both phase 2 and 3 should run with just 1 thread. How would you recommend going about resolving this?
 
Note: I am using a version of Sylvan from before the recent API breaking changes for compatibility reasons. (commit 5e9da7)

Thanks!
Aditya

**Comment by trolando** [comment]
Hi, this is correct behavior.

The Lace framework takes 100% CPU always because it uses busy waiting for work to execute. This is by design, as it is expected that the user is interested in maximal performance. Fortunately, you can suspend Lace (`lace_suspend`) and resume it again later (`lace_resume`) which should be perfect for your use case.
