### ISSUE TITLE
About overhead of sylvanExist function (again)

### ISSUE THREAD

**Issue by zhangyedi** [trolando/sylvan#24]
Hi, I find this issue again...

When I monitored the "Bdd::ExistAbstract" Function, I found that, as the number of workers increases, so does the computational overhead of the "sylvan_exist(cube)" function, as well as sylvan_and_exist(sylvan_true, cube).

Logically, I think it should be that the more workers there are, the faster the function runs.

**Comment by trolando** [comment]
Yes, but sometimes there is a bit more overhead from slightly more work done. You can turn on `SYLVAN_STATS` to see if the number of tasks is what you expect. Also, sometimes more workers does not result in faster execution, when the amount of work does not parallelize well. And how do you compute computational overhead? Do you have a concrete example of performance regression?

**Comment by trolando** [comment]
I have now found that there was a performance bug in an earlier version and this is now fixed.
