### ISSUE TITLE
Avoiding memory usage spike when using multi-precision

### ISSUE THREAD

**Issue by allrtaken** [trolando/sylvan#25]
Hello,

I am running into an issue with memory when using Sylvan with multi-precision (GMP) enabled. I notice that the memory usage spikes very quickly and I sometimes encounter the following error:

GNU MP: Cannot reallocate memory (old_size=8 new_size=3088)

Since the memory usage is reasonable when not using GMP, I assume the reason is because of the overhead of having to store large precision numbers. I wanted to check if you think this is the likely case or if there is an alternative explanation. Either way, is there any workaround to this problem? For example, I am currently initializing Sylvan with Table ratio 1 and Init ratio 10 -- will it help to use some other values?

Thanks,
Aditya

**Comment by trolando** [comment]
I doubt the table values are the issue, you could consider a smaller cache compared to the nodes table or forcing cache clears with `sylvan_gc` but ultimately the GMP library is going to need a lot of memory for infinite precision numbers. Have you tried using memory profiling to see where all memory is going?
