### ISSUE TITLE
operator== and operator!= should be boolean

### ISSUE THREAD

**Issue by michaelcadilhac** [trolando/sylvan#26]
https://github.com/trolando/sylvan/blob/6f7c0a2b979b0876294c34e0c8da569a3cde8115/src/sylvan_obj.hpp#L82

This can prevent auto inference of `operator==` and `operator!=` in classes that have a `Bdd` field. Not entirely sure after some testing, but in any case, is there a reason why they aren't bool?

**Comment by trolando** [comment]
They should be bool I think, there is no reason why they are int. Except me being a bad C++ programmer, I guess.

**Comment by trolando** [comment]
hopefully fixed now in
