### ISSUE TITLE
Support for Apple silicon

### ISSUE THREAD

**Issue by alaarman** [trolando/sylvan#33]
Sylvan does not yet support the new M1 chip.

**Comment by alaarman** [comment]
E.g. fence instruction doesn't compile, but probably more needs to change to support other memory models.

**Comment by alaarman** [comment]
Actually, this quick fix seems to work suspiciously well: consistent results for nqueens 10 on 18 threads.

diff --git a/src/lace.h b/src/lace.h
index 0b4b7a0..d5c6d38 100644
--- a/src/lace.h
+++ b/src/lace.h
@@ -322,7 +322,7 @@ void lace_yield(WorkerP *__lace_worker, Task *__lace_dq_head);
 #endif
 
 #ifndef mfence
-#define mfence() { asm volatile("mfence" ::: "memory"); }
+#define mfence() { asm volatile("dmb ish" ::: "memory"); }
 #endif
 
 /* Compiler specific branch prediction optimization */

**Comment by trolando** [comment]
I'm now working on proper support (without assembly macros) in the cross compile branch.

**Comment by alaarman** [comment]
This works for LTSmin:

https://github.com/alaarman/ltsmin/commit/53eba912a392e7b5dfa20e5c839c30926f689052

**Comment by trolando** [comment]
Support is now provided in Sylvan by using C11 atomics.
