### ISSUE TITLE
Error during cmake: "Failed to get the hash for HEAD"

### ISSUE THREAD

**Issue by Codermann63** [trolando/sylvan#44]
I'm having trouble getting cmake to create the make file of Sylvan v1.8.1.
It giving me "Failed to get the hash for HEAD:". The error comes from CMakeLists.txt:19 (when fetching lace.). I've included a screenshot of the terminal:

![error](https://github.com/trolando/sylvan/assets/96649204/95be5058-d15b-40de-bcd1-dbba6eac5cf6)

Ekstra info: I have no trouble with v.1.8.0.

**Comment by trolando** [comment]
Yeah I don't understand why this occurs. What happens if you kill the build directory and start all over again?

An alternative is simply compiling and installing Lace separately and then CMake can find it in /usr/local/

**Comment by Codermann63** [comment]
I tried creating a new ubuntu with the dependencies for ltsmin, getting sylvan from git and running "cmake -S . -B ."? It gives the same error.

**Comment by trolando** [comment]
Well I just tried to run it on my Linux Mint 21 installation, just sylvan, and it works fine. Tried multiple times. Maybe you can increase verbosity or something to figure out why it can't download Lace by looking at log files. By the way I would not recommend `cmake -B .`, you want to have a separate build directory, like `cmake -B build .` or similar.
In any case this can be avoided by manually compiling and installing lace:

- `git clone https://github.com/trolando/lace`
- `cd lace`
- `cmake -B build . -DCMAKE_BUILD_TYPE=Release`
- `cmake --build build`
- `sudo cmake --install build`

**Comment by Codermann63** [comment]
It doesn't work installing lace seperately.
BUT i found the problem, i am running cmake version 3.22.1 and FIND_PACKAGE_ARGS is a 3.24 feature. 

I have a kind of annoying request as the lastest version of cmake on ubuntu apt is 3.22.1, it would increate the difficulty to setup sylvan on ubuntu if you just bump the cmake_minimum_required to 3.24.

Could you either remove the FIND_PACKAGE_ARGS feature 
or
put it in some kind of conditional to check if the version is 3.24 or greater? Something like this:
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.24")
    FetchContent_Declare(
        lace
        GIT_REPOSITORY https://github.com/trolando/lace.git
        GIT_TAG        v1.4.1
        FIND_PACKAGE_ARGS
    )
else()
    FetchContent_Declare(
        lace
        GIT_REPOSITORY https://github.com/trolando/lace.git
        GIT_TAG        v1.4.1
    )
endif()

**Comment by trolando** [comment]
Eh, that would be possible yes. I would much rather have the minimum version of CMake to 3.24, but I see that Ubuntu only includes that version starting in Ubuntu 23.04, which is not LTS.

I can for now apply your suggestion so that people can install Sylvan without needing to install a newer CMake (available on snap, for example). 

Fixed in c1fceac.
